# Generated by Django 4.0 on 2022-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('a', 'ongoing'), ('c', 'stalled'), ('b', 'completed')], max_length=15),
        ),
    ]
