# Generated by Django 4.0 on 2022-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_rename_image_project_first_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_contributor',
            field=models.ImageField(default='/female_image.png', upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_contributor',
            field=models.ImageField(default='/female_image.png', upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_contributor',
            field=models.ImageField(default='/female_image.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
